### ISSUE TITLE
Expand yaml parsing error message

### ISSUE THREAD

**Issue by johanoskarsson** [zohmg/zohmg#1]
If the dataset.yaml parsing fails an error like this is printed:
[Mon Jun  1 14:48:42 2009] Error: Could not read configuration.
It doesn't tell the user what file was broken and doesn't include the error message from the exception: 
mapping values are not allowed here
  in "config/dataset.yaml", line 2, column 15

**Comment by fredrik** [comment]
closed by 73b127c120e96336c08b8ade46b64e221a747d7d
