### ISSUE TITLE
Import warning on python install.py

### ISSUE THREAD

**Issue by johanoskarsson** [zohmg/zohmg#2]
On python 2.6, Ubuntu 32bit 9.04 the following import error is shown at the end of the install.py run:

installing zohmg
build/bdist.linux-i686/egg/zohmg/utils.py:26: SyntaxWarning: import \* only allowed at module level
  def create_or_bust(c, t, cfs=['fam']):  
Copying zohmg-0.0.1-py2.6.egg to /usr/local/lib/python2.6/dist-packages  
Installing zohmg script to /usr/local/bin  
testing zohmg script..ok!

**Comment by fredrik** [comment]
fixed with 591b5b30d1554a1811461ae578d064760249c36f
