### ISSUE TITLE
usermapper function should be called mapper (or other), not map

### ISSUE THREAD

**Issue by fredrik** [zohmg/zohmg#21]
map is a built-in python function(!)

**Comment by tims** [comment]
Just thinking would be more dumbotic, if the user defined mapper yielded just a key and a tuple? eg:

  yield timestamp, (dimensions, values)

Then we could say use the dumbo identity mapper on the output of a normal dumbo program.

**Comment by fredrik** [comment]
I'm still not convinced when and why you would use the identity mapper. But as we discussed offline, it probably is less confusing if we were to tuple up time & dimensions like so: yield (time, dimensions), values
