### ISSUE TITLE
Hard to see if install script cannot fetch debs

### ISSUE THREAD

**Issue by johanoskarsson** [zohmg/zohmg#3]
If the install script cannot install the python debian packages it prints the following error msg:

E: Couldn't find package python-yaml
problems apt-getting packages!
please make sure you install the following packages or their equivalents:
- python-setuptools
- python-paste
- python-simplejson
- python-yaml

However, it continues straight away and ultimately fails further down. This is hard to see as a user. It should either pause or exit when the first error appears.

**Comment by fredrik** [comment]
closed by 3acaa5792dcf49b820886457d0d6bdf3dd692b2e
