### ISSUE TITLE
Installation process freezes for a long perid

### ISSUE THREAD

**Issue by johanoskarsson** [zohmg/zohmg#4]
Console says:
installing zohmg

And then stops for a long period. After a while this shows up:

error: Download error: (110, 'Connection timed out')
errors?!

It doesn't say what it was trying to download. Looks like it's dumbo and something fails. Retries has been known to work.

**Comment by fredrik** [comment]
we hand over control to easy_install. it is when easy_install downloads the source that this freeze might occur. am informing the user of the whereabouts of the logs (to where we pipe the verbose easy_install output). we can not reasonably do much more about this.
